FROM arm64v8/debian:trixie-slim

#
# Changing the version here requires a change in
# rq-lidar-april/image/rq-partitions/bdebstrap/customize30-configure
#
LABEL version="3"

LABEL description="rpi-image-gen"
LABEL maintainer="Bill Mania <bill@manialabs.us>"
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get dist-upgrade -y

RUN apt-get install -y \
    git \
    tree \
    vim

WORKDIR /opt
RUN git clone https://github.com/raspberrypi/rpi-image-gen.git

WORKDIR /opt/rpi-image-gen
RUN ./install_deps.sh
WORKDIR /opt
RUN git clone https://github.com/billmania/roboquest_addons.git
RUN ln -s /opt/roboquest_addons/rpi-image-gen/rq-lidar-april /opt/rpi-image-gen/rq-lidar-april
WORKDIR /opt/rpi-image-gen

ENTRYPOINT ["/bin/bash", "--login"]
