FROM ros:humble-ros-base

LABEL version="1"
LABEL description="ROS2 RoboQuest backend"
LABEL maintainer="Bill Mania <bill@manialabs.us>"
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "America/Los_Angeles" > /etc/timezone

RUN echo "source /opt/ros/humble/setup.bash" >> /etc/profile

SHELL ["/bin/bash", "--login", "-c"]
RUN apt-get update \
    && apt-get dist-upgrade -y
RUN apt-get install -y \
    apt-utils \
    vim \
    v4l-utils
RUN apt-get install -y \
    python3-colcon-ros \
    python3-smbus \
    python3-rpi.gpio \
    python3-networkmanager

WORKDIR /usr/src/ros2ws
RUN mkdir src

COPY src/roboquest_core src/roboquest_core/

CMD ["/bin/bash", "--login"]
