FROM ros:humble-ros-base

LABEL version="4"
LABEL description="ROS2 RoboQuest frontend"
LABEL maintainer="Bill Mania <bill@manialabs.us>"
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "America/Los_Angeles" > /etc/timezone

RUN echo "source /opt/ros/humble/setup.bash" >> /etc/profile

SHELL ["/bin/bash", "--login", "-c"]
RUN apt-get update \
    && apt-get dist-upgrade -y
RUN apt-get install -y \
    apt-utils \
    curl \
    vim
RUN apt-get install -y \
    python3-colcon-ros

WORKDIR /tmp
RUN curl --output node-v18.16.0-linux-arm64.tar.gz \
      https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-arm64.tar.gz \
      && curl --output SHASUM256.txt \
           https://nodejs.org/dist/v18.16.0/SHASUMS256.txt
RUN grep node-v18.16.0-linux-arm64.tar.gz SHASUM256.txt \
      | sha256sum -c -
WORKDIR /usr/local
RUN tar xzf /tmp/node-v18.16.0-linux-arm64.tar.gz
RUN echo "PATH=$PATH:/usr/local/node-v18.16.0-linux-arm64/bin" >> /etc/profile

RUN ln -sf /bin/bash /bin/sh
RUN useradd -ms /bin/bash roboquest
RUN chown roboquest /usr/src
USER roboquest

WORKDIR /usr/src/ros2ws/src

RUN git clone -b main https://github.com/billmania/roboquest_ui.git
RUN git clone -b main https://github.com/billmania/rq_msgs.git
WORKDIR /usr/src/ros2ws
#
# The rq_msgs package must be built so the messages and services are
# available to the generate_messages.sh script.
#
RUN colcon build --packages-select rq_msgs

ENV PATH="${PATH}:/usr/local/node-v18.16.0-linux-arm64/bin"
WORKDIR /usr/src/ros2ws/src/roboquest_ui
#
# Now the NodeJS modules required by roboquest_ui must be installed. This
# includes the rclnodejs-cli module with its option to generate ROS
# messages.
#
RUN npm i
COPY src/roboquest_ui/generate_messages.sh generate_messages.sh
RUN ./generate_messages.sh

#
# And finally the roboquest_ui package can be built and installed. The
# process installs all of the necessary rclnodejs components.
#
WORKDIR /usr/src/ros2ws
RUN colcon build --packages-select rq_msgs roboquest_ui

WORKDIR /usr/src/ros2ws
CMD ["/bin/bash", "--login"]
